### ISSUE TITLE
Add polar pan start/stop to ICD

### ISSUE THREAD

**Issue by DevanTurtle7** [talos-rit/project_documentation#3]
Add a Polar Pan Start command and a Polar Pan Stop command to the ICD. The arm will continuously rotate after it receives a polar pan start command, until it receives a polar pan stop command. This will be used in the manual interface so that users are able to rotate the arm while a button is being held down.

**Comment by bl2060** [comment]
I have one concern, with a potential solution:
To account for potentially dropped PolarPanStop commands, the operator should stop after a certain amount of time. To avoid a time out, another polar pan start (or potentially polar pan continue) command should be issued before the timeout is supposed to expire. This method could potentially also be implemented with existing polar pan commands, but there is some utility in separating the two, so I'm good with either approach.
